import './globals.css'
import {Inter, Poppins} from 'next/font/google'
import Navbar from "@/components/Navbar";
import {SmoothScrollProvider} from "@/context/SmoothScrollProvider";
import Footer from "../components/common/Footer";

const inter = Poppins({subsets: ['latin'], weight: "400"})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }) {
    return (
        <html lang="en">
        <body className={`${inter.className} bg-bg container lg:px-20 m-auto `}>
        <Navbar/>
        <SmoothScrollProvider>
            <main className={''} id="my-scroll">
                {children}

            </main>
        </SmoothScrollProvider>
        <Footer/>

        </body>
        </html>
    )
}
